{
  "permissions": {
    "allow": [
      "Bash(git fetch:*)",
      "Bash(gcloud compute:*)",
      "Read(//d/Perforce/SB2/Workspace/Internal/SB2/Plugins/**)",
      "Read(//d/Perforce/SB2/Workspace/Internal/Engine/Plugins/**)",
      "Bash(powershell -Command \"[Environment]::GetEnvironmentVariable\\('UE_ADDITIONAL_PLUGIN_DIRS','User'\\)\")",
      "Read(//d/Perforce/SB2/Workspace/Internal/SB2/**)",
      "Bash(gh api:*)",
      "Bash(npx -y @upstash/context7-mcp --help)",
      "Bash(claude mcp *)",
      "Bash(git add *)",
      "Bash(git commit -m ' *)",
      "Bash(git push *)",
      "Bash(curl -s -m 3 http://localhost:9316/mcp -X POST -H \"Content-Type: application/json\" -H \"Accept: application/json, text/event-stream\" -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"2024-11-05\",\"capabilities\":{},\"clientInfo\":{\"name\":\"t\",\"version\":\"1\"}}}')",
      "Bash(curl -s -m 3 http://localhost:3000/)",
      "Bash(curl -s -m 5 http://localhost:9316/mcp -X POST -H \"Content-Type: application/json\" -H \"Accept: application/json, text/event-stream\" -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"2024-11-05\",\"capabilities\":{},\"clientInfo\":{\"name\":\"t\",\"version\":\"1\"}}}')",
      "Bash(curl -s http://localhost:3000/health --max-time 5)",
      "Bash(curl -s -o /dev/null -w \"HTTP %{http_code}\\\\n\" http://localhost:3000/ --max-time 5)",
      "Bash(curl -s http://localhost:9316/tools --max-time 5)",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H \"Content-Type: application/json\" -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"id\":1,\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"add_node\",\"params\":{\"node_type\":\"VariableGet\"}}}}' --max-time 10)",
      "Bash(python -c \"import sys,json; print\\(json.load\\(sys.stdin\\)['result']['content'][0]['text']\\)\")",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"id\":1,\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"add_node\",\"params\":{\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_BP\",\"graph_name\":\"EventGraph\",\"node_type\":\"VariableGet\",\"variable_name\":\"BaseMeshZ\",\"position\":[400,1400]}}}}' --max-time 15)",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"id\":1,\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"remove_node\",\"params\":{\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_BP\",\"graph_name\":\"EventGraph\",\"node_id\":\"K2Node_VariableGet_17\"}}}}' --max-time 10)",
      "Bash(python -c \"import sys,json; print\\(json.load\\(sys.stdin\\)['result']['content'][0]['text'][:200]\\)\")",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"id\":1,\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"add_node\",\"params\":{\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_BP\",\"graph_name\":\"UpdateMeshOffsetZ\",\"node_type\":\"CallFunction\",\"function_name\":\"K2_GetActorLocation\",\"position\":[400,0]}}}}' --max-time 15)",
      "Bash(python -c \"import sys,json; d=json.load\\(sys.stdin\\); print\\(d['result']['content'][0]['text'][:300]\\)\")",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"id\":1,\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"remove_node\",\"params\":{\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_BP\",\"graph_name\":\"UpdateMeshOffsetZ\",\"node_id\":\"K2Node_CallFunction_1\"}}}}' --max-time 10)",
      "Bash(python -c \"import sys,json; d=json.load\\(sys.stdin\\); print\\(d['result']['content'][0]['text'][:100]\\)\")",
      "Bash(chmod +x /c/Dev/Sanjuk-Unreal/scripts/build_mesh_z_graph.sh)",
      "Bash(/c/Dev/Sanjuk-Unreal/scripts/build_mesh_z_graph.sh)",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"id\":1,\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"remove_node\",\"params\":{\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_BP\",\"graph_name\":\"UpdateMeshOffsetZ\",\"node_id\":\"K2Node_CallFunction_5\"}}}}' --max-time 10)",
      "Bash(sed -i 's/\"struct_name\":/\"struct_type\":/g' /c/Dev/Sanjuk-Unreal/scripts/build_mesh_z_graph.sh)",
      "Bash(sed 's/\"struct_name\":/\"struct_type\":/g' /c/Dev/Sanjuk-Unreal/scripts/build_mesh_z_graph.sh)",
      "Bash(mv /tmp/script_new.sh /c/Dev/Sanjuk-Unreal/scripts/build_mesh_z_graph.sh)",
      "Bash(python -c ' *)",
      "Bash(python)",
      "Bash(python scripts/connect_mesh_z.py)",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"id\":1,\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"compile_blueprint\",\"params\":{\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_BP\"}}}}' --max-time 30)",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"id\":1,\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"get_node_details\",\"params\":{\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_BP\",\"graph_name\":\"EventGraph\",\"node_id\":\"K2Node_ExecutionSequence_1\"}}}}' --max-time 15)",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H \"Content-Type: application/json\" -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"get_variables\",\"target\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_ABP\"}}}')",
      "Bash(python3 -c \" import sys,json data=json.load\\(sys.stdin\\) content=data.get\\('result',{}\\).get\\('content',[]\\) for c in content: print\\(c.get\\('text',''\\)[:8000]\\) \")",
      "Bash(python -m json.tool)",
      "WebSearch",
      "WebFetch(domain:dev.epicgames.com)",
      "WebFetch(domain:edwardbeazer.com)",
      "WebFetch(domain:kinemation.gitbook.io)",
      "WebFetch(domain:x157.github.io)",
      "WebFetch(domain:www.aaronkemner.com)",
      "WebFetch(domain:jaydengames.com)",
      "WebFetch(domain:github.com)",
      "WebFetch(domain:forums.unrealengine.com)",
      "WebFetch(domain:www.yuewu.dev)",
      "WebFetch(domain:shatteredmirrorstudio.com)",
      "WebFetch(domain:docs.motionco.re)",
      "WebFetch(domain:davinsaputra.artstation.com)",
      "WebFetch(domain:www.unrealengine.com)",
      "WebFetch(domain:gist.github.com)",
      "WebFetch(domain:www.unreal-university.blog)",
      "WebFetch(domain:jiahaoli.org)",
      "WebFetch(domain:80.lv)",
      "Bash(netstat -ano)",
      "Bash(tasklist)",
      "Bash(powershell *)",
      "Read(//c/Dev/GASP-DAO-Overlay//**)",
      "Read(//c/Dev/GASP-DAO-Overlay/Content/DAO//**)",
      "Bash(cp *)",
      "Bash([ -f \"$GASP_GT\" ])",
      "Bash(echo '+GameplayTagTableList=/Game/DAO/Blueprints/Data/GT_DAO_States.GT_DAO_States')",
      "Bash(git commit *)",
      "Bash(curl *)",
      "Bash(python *)",
      "Bash(grep -oE \"^/Script/[A-Za-z]+\\\\.[A-Z][A-Za-z_]+$\")",
      "Bash(grep -oE \"^\\(Event_[A-Za-z_]+|Execute[A-Za-z_]*|Update[A-Za-z_]*|Begin[A-Za-z_]*|OnUpdate|OnEvaluate\\)$\")",
      "Bash(grep -oE \"^Crowd[A-Za-z_]+$\")",
      "Read(//c/dev/**)",
      "Bash(tar czf *)",
      "Read(//tmp/**)",
      "Bash(bash scripts/claude-sync.sh status)",
      "Bash(node scripts/hooks/pre-prompt-gcp-download.js)",
      "Bash(node scripts/hooks/post-edit-memory-upload.js)",
      "Bash(bash scripts/claude-sync.sh upload)",
      "Bash(bash scripts/claude-sync.sh download)",
      "Bash(wmic OS get FreePhysicalMemory,TotalVisibleMemorySize /format:value)",
      "Bash(cp E:/Perforce/SB2/Workspace/Internal/SB2/Plugins/Monolith/Config/MonolithSettings.ini E:/Perforce/SB2/Workspace/Internal/SB2/Plugins/Monolith/Config/MonolithSettings.ini.bak-__TRACKED_VAR__)",
      "Bash(cp E:/Perforce/SB2/Workspace/Internal/SB2/Config/DefaultMonolith.ini E:/Perforce/SB2/Workspace/Internal/SB2/Config/DefaultMonolith.ini.bak-__TRACKED_VAR__)",
      "Bash(attrib -R \"E:\\\\Perforce\\\\SB2\\\\Workspace\\\\Internal\\\\SB2\\\\Plugins\\\\Monolith\\\\Saved\\\\ProjectIndex.db\")",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"animation_query\",\"arguments\":{\"action\":\"get_graphs\",\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_ABP\"}}}')",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"animation_query\",\"arguments\":{\"action\":\"get_linked_layers\",\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_ABP\"}}}')",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"get_interfaces\",\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_AnimLayer_IK\"}}}')",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"get_parent_class\",\"asset_path\":\"/Game/ART/Character/PC/PC_01/Blueprint/PC_01_AnimLayer_IK\"}}}')",
      "Bash(grep -iE \"mesh_z|offset|interp\" echo \"---\" git log --oneline --all -20)",
      "Bash(grep -iE \"^.?Cost|Cost$|.*Cost.*\")",
      "Bash(grep -E \"^[A-Za-z_][A-Za-z0-9_/\\\\.]{4,}\")",
      "Bash(xargs -I '{}' sh -c 'name=$\\(basename \"{}\"\\); if echo \"$name\" | grep -iqE \"chooser|ct_|choose\"; then echo \"{}\"; fi')",
      "Bash(xargs -I '{}' sh -c 'name=$\\(basename \"{}\"\\); if echo \"$name\" | grep -iqE \"overlay|pose_state\"; then echo \"{}\"; fi')",
      "Bash(grep -v \"^$\")",
      "Bash(awk 'length>0')",
      "Read(//e/Perforce/SB2/Workspace/Internal/SB2/Content/**)",
      "Bash(powershell.exe *)",
      "Bash(grep -Ei \"^[A-Z][A-Za-z]+$\")",
      "Bash(python3 -c \"import json, sys; data=json.load\\(sys.stdin\\); tools=data['result']['tools']; bp=[t for t in tools if t['name']=='blueprint_query'][0]; print\\(json.dumps\\(bp['inputSchema'], indent=2\\)[:3000]\\)\")",
      "Bash(python3 -m json.tool)",
      "Bash(python3 -c \"import json, sys; d=json.load\\(sys.stdin\\); txt=d['result']['content'][0]['text']; p=json.loads\\(txt\\); [print\\(k, '=', json.dumps\\(v, indent=2, ensure_ascii=False\\)\\) for k,v in p.items\\(\\) if 'pelvis' in k.lower\\(\\) or 'pelvis' in str\\(v\\).lower\\(\\)[:100]]\")",
      "Bash(mkdir -p /c/temp)",
      "Read(//c/temp/**)",
      "Bash([ -f \"scripts/$f\" ])",
      "Bash(git mv *)",
      "Bash(git check-ignore *)",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\",\"params\":{}}')",
      "Bash(python3 -c ' *)",
      "Read(//c//**)",
      "Bash(mkdir -p /c/tmp)",
      "Read(//c/tmp/**)",
      "Bash(awk 'length\\($0\\)>=6')",
      "mcp__monolith__monolith_status",
      "mcp__monolith__animation_query",
      "mcp__monolith__monolith_discover",
      "Read(//e/Perforce/SB2/Workspace/Internal/SB2/**)",
      "Read(//e/Perforce/SB2/Workspace/Internal/SB2/Plugins/Monolith/**)",
      "Read(//c/Users/SHIFTUP/Documents/oCam/**)",
      "Bash(mkdir -p C:/temp)",
      "Bash(curl -s -X POST http://localhost:9316/mcp -H \"Content-Type: application/json\" -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"blueprint_query\",\"arguments\":{\"action\":\"get_cdo_properties\",\"params\":{\"asset_path\":\"/Game/Art/Character/PC/PC_01/Equipment/Hair/PC_01_Hair_01/PC_01_Hair_Sanjuk\"}}}}')",
      "Bash(echo \"EXIT: $?\")",
      "Bash(echo \"EXIT:$?\")",
      "Read(//c/Users/SHIFTUP/AppData/Local/Temp/claude/C--Dev-Sanjuk-Unreal/e9a5e390-a8cb-448d-ab6b-737b84ad0124/tasks/**)",
      "Bash(git log *)",
      "Bash(grep -oE '\\(\"title\":\"[^\"]{1,80}\"\\)' C:/Dev/Sanjuk-Unreal/dumps/setblendstack.json)",
      "Bash(grep -oE '\\\\\\\\\"title\\\\\\\\\":\\\\\\\\\"[^\\\\\\\\]*\\\\\\\\\"' C:/Dev/Sanjuk-Unreal/dumps/setblendstack.json)",
      "Bash(awk 'length\\($0\\) >= 6')",
      "Bash(awk 'length\\($0\\) >= 8')",
      "Bash(grep -vE \"^[/_]$|^.$|^..$|^...$\")",
      "mcp__monolith__project_query",
      "Bash(attrib *)",
      "PowerShell(Test-Path *)",
      "PowerShell(git clone *)",
      "PowerShell(& python -m venv C:\\\\Dev\\\\MayaMCP\\\\.venv; & C:\\\\Dev\\\\MayaMCP\\\\.venv\\\\Scripts\\\\python.exe -m pip install --upgrade pip; & C:\\\\Dev\\\\MayaMCP\\\\.venv\\\\Scripts\\\\python.exe -m pip install -r C:\\\\Dev\\\\MayaMCP\\\\requirements.txt)",
      "PowerShell(New-Item *)",
      "Bash(C:\\\\Program Files\\\\Autodesk\\\\Maya2023\\\\bin\\\\mayapy.exe *)",
      "PowerShell(Get-ChildItem 'E:\\\\Maya\\\\maya_script\\\\Groom_Hair_Manager' | Select-Object Name, Length, LastWriteTime | Format-Table -AutoSize; \"---\"; \\(Get-Content 'E:\\\\Maya\\\\maya_script\\\\Groom_Hair_Manager\\\\ANALYSIS.md' | Measure-Object -Line\\).Lines.ToString\\(\\) + \" lines\")",
      "PowerShell(& C:\\\\Dev\\\\MayaMCP\\\\.venv\\\\Scripts\\\\python.exe -m pip install markdown pygments --quiet; \"installed\")",
      "PowerShell(& C:\\\\Dev\\\\MayaMCP\\\\.venv\\\\Scripts\\\\python.exe E:\\\\Maya\\\\maya_script\\\\Groom_Hair_Manager\\\\_build_pdf.py)",
      "mcp__monolith__blueprint_query",
      "Bash(grep *)",
      "mcp__monolith__source_query",
      "mcp__monolith__scripting_query",
      "Bash(Get-Item C:\\\\Dev\\\\Sanjuk-Unreal\\\\Saved\\\\drawdebug_nodes.json)",
      "Bash(Select-Object Length)",
      "Bash(python3 *)",
      "Bash(git pull *)",
      "Bash(py *)",
      "mcp__monolith__editor_query",
      "Bash(xargs echo \"## 섹션 수:\")",
      "Bash(echo \"===EXIT $?===\")",
      "mcp__claude_ai_Atlassian__searchConfluenceUsingCql",
      "mcp__claude_ai_Atlassian__getConfluencePage"
    ]
  },
  "enableAllProjectMcpServers": true,
  "enabledMcpjsonServers": [
    "monolith",
    "unreal-mcp",
    "unrealclaude-bridge",
    "context7",
    "confluence",
    "maya"
  ]
}
