"""Generate T3D paste chunks for STEP 1 (evade peak walk mode latch).

Outputs:
- dumps/evade/step1_updatevariables_paste.t3d  (13 nodes for UpdateVariables)
- dumps/evade/step1_animrec_emit_paste.t3d     (FormatText splice for epwm/rpwm)
"""
import uuid


def guid32():
    """Return 32-hex uppercase string (UE K2Node pin id format)."""
    return uuid.uuid4().hex.upper()


def node_guid():
    """NodeGuid: 'A(B)CDEF...' 32 hex uppercase, same format as pin."""
    return uuid.uuid4().hex.upper()


# --- Shared utility ---------------------------------------------------------

def varget_byte(name, posx, posy, node_name, out_links):
    """K2Node_VariableGet for byte-typed variable. out_links: list of 'NodeName PinId' refs."""
    pin_id = guid32()
    linked = "".join(f"(LinkedTo=(EdGraphPin'\"{l}\"',))" for l in out_links)
    # Use proper LinkedTo array syntax
    linked_str = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    return pin_id, f"""Begin Object Class=/Script/BlueprintGraph.K2Node_VariableGet Name="{node_name}"
   VariableReference=(MemberName="{name}",bSelfContext=True)
   NodePosX={posx}
   NodePosY={posy}
   NodeGuid={node_guid()}
   CustomProperties Pin (PinId={pin_id},PinName="{name}",Direction="EGPD_Output",PinType.PinCategory="byte",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="0",AutogeneratedDefaultValue="0",LinkedTo=({linked_str}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object"""


def varget_bool(name, posx, posy, node_name, out_links):
    pin_id = guid32()
    linked_str = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    return pin_id, f"""Begin Object Class=/Script/BlueprintGraph.K2Node_VariableGet Name="{node_name}"
   VariableReference=(MemberName="{name}",bSelfContext=True)
   NodePosX={posx}
   NodePosY={posy}
   NodeGuid={node_guid()}
   CustomProperties Pin (PinId={pin_id},PinName="{name}",Direction="EGPD_Output",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({linked_str}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object"""


def varset_byte(name, posx, posy, node_name, exec_in_links, then_links, value_in_links):
    """K2Node_VariableSet for byte. Returns (exec_in_pin, then_pin, value_in_pin, node_text)."""
    exec_pin = guid32()
    then_pin = guid32()
    value_pin = guid32()
    out_get_pin = guid32()
    self_pin = guid32()
    exec_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in exec_in_links)
    then_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in then_links)
    value_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in value_in_links)
    return exec_pin, then_pin, value_pin, f"""Begin Object Class=/Script/BlueprintGraph.K2Node_VariableSet Name="{node_name}"
   VariableReference=(MemberName="{name}",bSelfContext=True)
   NodePosX={posx}
   NodePosY={posy}
   NodeGuid={node_guid()}
   CustomProperties Pin (PinId={exec_pin},PinName="execute",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=({exec_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={then_pin},PinName="then",Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=({then_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={value_pin},PinName="{name}",PinType.PinCategory="byte",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="0",AutogeneratedDefaultValue="0",LinkedTo=({value_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={out_get_pin},PinName="Output_Get",Direction="EGPD_Output",PinType.PinCategory="byte",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="0",AutogeneratedDefaultValue="0",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={self_pin},PinName="self",PinFriendlyName=NSLOCTEXT("K2Node","Self","Target"),PinToolTip="Target\\nAnim Instance Reference",PinType.PinCategory="object",PinType.PinSubCategory="",PinType.PinSubCategoryObject=BlueprintGeneratedClass'"/Game/Art/Character/PC/PC_01/Blueprint/PC_01_ABP.PC_01_ABP_C"',PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object"""


def branch(node_name, posx, posy, exec_in_links, cond_in_links, then_links, else_links):
    exec_pin = guid32()
    cond_pin = guid32()
    then_pin = guid32()
    else_pin = guid32()
    exec_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in exec_in_links)
    cond_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in cond_in_links)
    then_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in then_links)
    else_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in else_links)
    return exec_pin, cond_pin, then_pin, else_pin, f"""Begin Object Class=/Script/BlueprintGraph.K2Node_IfThenElse Name="{node_name}"
   NodePosX={posx}
   NodePosY={posy}
   NodeGuid={node_guid()}
   CustomProperties Pin (PinId={exec_pin},PinName="execute",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=({exec_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={cond_pin},PinName="Condition",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="true",AutogeneratedDefaultValue="true",LinkedTo=({cond_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={then_pin},PinName="then",Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=({then_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={else_pin},PinName="else",Direction="EGPD_Output",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=({else_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object"""


def not_bool(node_name, posx, posy, a_in_links, out_links):
    """K2Node_CallFunction Not_PreBool (KismetMathLibrary)."""
    exec_in_not = None  # pure function, no exec pins
    a_pin = guid32()
    ret_pin = guid32()
    self_pin = guid32()
    a_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in a_in_links)
    ret_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    return a_pin, ret_pin, f"""Begin Object Class=/Script/BlueprintGraph.K2Node_CallFunction Name="{node_name}"
   bIsPureFunc=True
   FunctionReference=(MemberParent=Class'"/Script/Engine.KismetMathLibrary"',MemberName="Not_PreBool")
   NodePosX={posx}
   NodePosY={posy}
   NodeGuid={node_guid()}
   CustomProperties Pin (PinId={self_pin},PinName="self",PinFriendlyName=NSLOCTEXT("K2Node","Target","Target"),PinToolTip="Target\\nKismet Math Library Reference",PinType.PinCategory="object",PinType.PinSubCategory="",PinType.PinSubCategoryObject=Class'"/Script/Engine.KismetMathLibrary"',PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultObject="/Script/Engine.Default__KismetMathLibrary",PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={a_pin},PinName="A",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({a_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={ret_pin},PinName="ReturnValue",Direction="EGPD_Output",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({ret_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object"""


def greater_byte(node_name, posx, posy, a_in_links, b_in_links, out_links):
    """K2Node_CallFunction Greater_ByteByte (KismetMathLibrary)."""
    a_pin = guid32()
    b_pin = guid32()
    ret_pin = guid32()
    self_pin = guid32()
    a_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in a_in_links)
    b_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in b_in_links)
    ret_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    return a_pin, b_pin, ret_pin, f"""Begin Object Class=/Script/BlueprintGraph.K2Node_CallFunction Name="{node_name}"
   bIsPureFunc=True
   FunctionReference=(MemberParent=Class'"/Script/Engine.KismetMathLibrary"',MemberName="Greater_ByteByte")
   NodePosX={posx}
   NodePosY={posy}
   NodeGuid={node_guid()}
   CustomProperties Pin (PinId={self_pin},PinName="self",PinFriendlyName=NSLOCTEXT("K2Node","Target","Target"),PinType.PinCategory="object",PinType.PinSubCategory="",PinType.PinSubCategoryObject=Class'"/Script/Engine.KismetMathLibrary"',PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultObject="/Script/Engine.Default__KismetMathLibrary",PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={a_pin},PinName="A",PinType.PinCategory="byte",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="0",AutogeneratedDefaultValue="0",LinkedTo=({a_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={b_pin},PinName="B",PinType.PinCategory="byte",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="0",AutogeneratedDefaultValue="0",LinkedTo=({b_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={ret_pin},PinName="ReturnValue",Direction="EGPD_Output",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({ret_linked}),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object"""


# =====================================================================
# UpdateVariables T3D — 13 nodes for evade peak walk mode latch
# =====================================================================
# Topology:
#
# Phase 1 — peak update (placed between VariableSet_43 and IfThenElse_2):
#   VarSet_43.then ─X─ IfThenElse_2.execute   (existing wire to break)
#   VarSet_43.then ──> Branch_NEW_1.execute   (= NOT HasEvade gate)
#       NOT(VG_HasEvade) ──> Branch_NEW_1.Condition
#       Branch_NEW_1.then  ──> Branch_NEW_2.execute  (= PendingWalkMode > RollingPeakWalkMode)
#           Greater_ByteByte(VG_PendingWalkMode, VG_RollingPeakWalkMode_A) → Branch_NEW_2.Condition
#           Branch_NEW_2.then ──> VarSet_RollingPeak.execute
#               VG_PendingWalkMode_B → VarSet_RollingPeak.RollingPeakWalkMode (data)
#               VarSet_RollingPeak.then ──> IfThenElse_2.execute  (merge)
#           Branch_NEW_2.else ──> IfThenElse_2.execute            (merge)
#       Branch_NEW_1.else  ──> IfThenElse_2.execute  (merge — evade active, skip update)
#
# Phase 2 — onset latch (between IfThenElse_2.then and VariableSet_56.execute):
#   IfThenElse_2.then ─X─ VariableSet_56.execute   (existing wire to break)
#   IfThenElse_2.then ──> VarSet_EvadePeak.execute
#       VG_RollingPeak_C → VarSet_EvadePeak.EvadePeakWalkMode (data)
#       VarSet_EvadePeak.then ──> VariableSet_56.execute
#
# Phase 3 — evade-end reset (between VariableSet_45.then and VariableSet_2.execute):
#   VariableSet_45.then ─X─ VariableSet_2.execute  (existing wire to break)
#   VariableSet_45.then ──> VarSet_RollingPeak_Reset.execute
#       VG_PendingWalkMode_C → VarSet_RollingPeak_Reset.RollingPeakWalkMode (data)
#       VarSet_RollingPeak_Reset.then ──> VariableSet_2.execute
#
# Node count: 6 VarGet + 1 NOT + 1 Greater_ByteByte + 2 Branch + 3 VarSet = 13 ✓

# Phase 1 nodes
# Layout: empty space at y=4700-4800 (above existing nodes at y=4912)
# x range: 1850-2600 (between VariableSet_43@1744 and IfThenElse_2@2704)

# Existing external node pin IDs (from dumps/evade/UpdateVariables.json).
# IMPORTANT: We do NOT emit external LinkedTo in T3D — UE paste creates one-sided links
# that compiler ignores or treats as orphan. User connects external wires manually
# after paste (8 wire ops total).
# These constants are kept for reference comments only, NOT used in LinkedTo arrays.
EXISTING_VS43_THEN_REF = "K2Node_VariableSet_43.then"
EXISTING_ITE2_EXECUTE_REF = "K2Node_IfThenElse_2.execute"
EXISTING_ITE2_THEN_REF = "K2Node_IfThenElse_2.then"
EXISTING_VS56_EXECUTE_REF = "K2Node_VariableSet_56.execute"
EXISTING_VS45_THEN_REF = "K2Node_VariableSet_45.then"
EXISTING_VS2_EXECUTE_REF = "K2Node_VariableSet_2.execute"

# Empty list — sentinel value indicating "leave LinkedTo=() so user wires manually after paste"
EXT = []  # noqa
# Replace all occurrences below: external links use [] (sentinel), internal use new-node pin refs.

# Aliases retained for grep but emit as empty lists:
EXISTING_VS43_THEN = None
EXISTING_ITE2_EXECUTE = None
EXISTING_ITE2_THEN = None
EXISTING_VS56_EXECUTE = None
EXISTING_VS45_THEN = None
EXISTING_VS2_EXECUTE = None

# Names for new nodes
N_VG_HASEVADE = "K2Node_VariableGet_NEW_HasEvade"
N_NOT = "K2Node_CallFunction_NEW_NotHasEvade"
N_VG_PWM_A = "K2Node_VariableGet_NEW_PendingWM_A"
N_VG_RPWM_A = "K2Node_VariableGet_NEW_RollingPeak_A"
N_GREATER = "K2Node_CallFunction_NEW_GreaterByte"
N_BR1 = "K2Node_IfThenElse_NEW_1"
N_BR2 = "K2Node_IfThenElse_NEW_2"
N_VG_PWM_B = "K2Node_VariableGet_NEW_PendingWM_B"
N_VS_RPWM_UPD = "K2Node_VariableSet_NEW_RollingPeak_Upd"
N_VG_RPWM_C = "K2Node_VariableGet_NEW_RollingPeak_C"
N_VS_EPWM = "K2Node_VariableSet_NEW_EvadePeak_Latch"
N_VG_PWM_C = "K2Node_VariableGet_NEW_PendingWM_C"
N_VS_RPWM_RESET = "K2Node_VariableSet_NEW_RollingPeak_Reset"

# Generate Phase 1 nodes. We must thread pin IDs in dependency order:
# 1) VarSets are created with placeholders, then we resolve wiring by recording pins.

# Step A: create VarSet_RollingPeak_Upd first (terminal of inner true branch),
#         since we need its exec pin for Branch2.then linkage.
vs_rpwm_upd_exec, vs_rpwm_upd_then, vs_rpwm_upd_value, vs_rpwm_upd_text = varset_byte(
    "RollingPeakWalkMode", 2400, 4700, N_VS_RPWM_UPD,
    exec_in_links=[],   # to be linked by Branch_NEW_2.then in Branch2 below
    then_links=[],  # link back to existing IfThenElse_2
    value_in_links=[],  # will receive VG_PWM_B
)

# VG_PendingWM_B -> VarSet_RollingPeak_Upd.value
vg_pwm_b_pin, vg_pwm_b_text = varget_byte(
    "PendingWalkMode", 2240, 4736, N_VG_PWM_B,
    out_links=[f"{N_VS_RPWM_UPD} {vs_rpwm_upd_value}"],
)
# Now VS_RPWM_UPD.value should link back to VG_PWM_B — patch the LinkedTo (regenerate text):
vs_rpwm_upd_exec, vs_rpwm_upd_then, vs_rpwm_upd_value, vs_rpwm_upd_text = varset_byte(
    "RollingPeakWalkMode", 2400, 4700, N_VS_RPWM_UPD,
    exec_in_links=[],   # filled by Branch2.then later (we'll use the pin id we just got)
    then_links=[],
    value_in_links=[f"{N_VG_PWM_B} {vg_pwm_b_pin}"],
)

# Greater_ByteByte: A=VG_PWM_A, B=VG_RPWM_A, Out -> Branch_NEW_2.Condition
# Branch_NEW_2 first to know cond pin
br2_exec, br2_cond, br2_then, br2_else, br2_text = branch(
    N_BR2, 2304, 4624,
    exec_in_links=[],  # filled by Branch_NEW_1.then below
    cond_in_links=[],  # filled by Greater Out
    then_links=[f"{N_VS_RPWM_UPD} {vs_rpwm_upd_exec}"],
    else_links=[],
)
gt_a, gt_b, gt_ret, gt_text = greater_byte(
    N_GREATER, 2128, 4592,
    a_in_links=[],  # VG_PWM_A
    b_in_links=[],  # VG_RPWM_A
    out_links=[f"{N_BR2} {br2_cond}"],
)
# Patch Branch2 cond_in:
br2_exec, br2_cond, br2_then, br2_else, br2_text = branch(
    N_BR2, 2304, 4624,
    exec_in_links=[],
    cond_in_links=[f"{N_GREATER} {gt_ret}"],
    then_links=[f"{N_VS_RPWM_UPD} {vs_rpwm_upd_exec}"],
    else_links=[],
)

# VG_PendingWM_A -> Greater.A
vg_pwm_a_pin, vg_pwm_a_text = varget_byte(
    "PendingWalkMode", 1936, 4576, N_VG_PWM_A,
    out_links=[f"{N_GREATER} {gt_a}"],
)
# VG_RollingPeak_A -> Greater.B
vg_rpwm_a_pin, vg_rpwm_a_text = varget_byte(
    "RollingPeakWalkMode", 1936, 4624, N_VG_RPWM_A,
    out_links=[f"{N_GREATER} {gt_b}"],
)
# Patch Greater A/B in:
gt_a, gt_b, gt_ret, gt_text = greater_byte(
    N_GREATER, 2128, 4592,
    a_in_links=[f"{N_VG_PWM_A} {vg_pwm_a_pin}"],
    b_in_links=[f"{N_VG_RPWM_A} {vg_rpwm_a_pin}"],
    out_links=[f"{N_BR2} {br2_cond}"],
)

# Branch_NEW_1: cond = NOT(HasEvade)
br1_exec, br1_cond, br1_then, br1_else, br1_text = branch(
    N_BR1, 2096, 4736,
    exec_in_links=[],  # comes from VariableSet_43.then (existing)
    cond_in_links=[],  # filled by NOT out
    then_links=[f"{N_BR2} {br2_exec}"],
    else_links=[],
)
# Now re-emit Branch_NEW_2 with the back-link to Branch_NEW_1.then (so paste wires both sides)
br2_exec, br2_cond, br2_then, br2_else, br2_text = branch(
    N_BR2, 2304, 4624,
    exec_in_links=[f"{N_BR1} {br1_then}"],  # back-link
    cond_in_links=[f"{N_GREATER} {gt_ret}"],
    then_links=[f"{N_VS_RPWM_UPD} {vs_rpwm_upd_exec}"],
    else_links=[],
)
# NOT(HasEvade)
not_a, not_ret, not_text = not_bool(
    N_NOT, 1936, 4768,
    a_in_links=[],  # VG_HasEvade
    out_links=[f"{N_BR1} {br1_cond}"],
)
br1_exec, br1_cond, br1_then, br1_else, br1_text = branch(
    N_BR1, 2096, 4736,
    exec_in_links=[],
    cond_in_links=[f"{N_NOT} {not_ret}"],
    then_links=[f"{N_BR2} {br2_exec}"],
    else_links=[],
)
# VG_HasEvade -> NOT.A
vg_hasevade_pin, vg_hasevade_text = varget_bool(
    "HasEvade", 1744, 4800, N_VG_HASEVADE,
    out_links=[f"{N_NOT} {not_a}"],
)
not_a, not_ret, not_text = not_bool(
    N_NOT, 1936, 4768,
    a_in_links=[f"{N_VG_HASEVADE} {vg_hasevade_pin}"],
    out_links=[f"{N_BR1} {br1_cond}"],
)

# Patch VS_RPWM_UPD.execute to come from Branch2.then
vs_rpwm_upd_exec, vs_rpwm_upd_then, vs_rpwm_upd_value, vs_rpwm_upd_text = varset_byte(
    "RollingPeakWalkMode", 2400, 4700, N_VS_RPWM_UPD,
    exec_in_links=[f"{N_BR2} {br2_then}"],
    then_links=[],
    value_in_links=[f"{N_VG_PWM_B} {vg_pwm_b_pin}"],
)

# Phase 2 — onset latch: IfThenElse_2.then -> Set EvadePeakWalkMode = RollingPeakWalkMode -> VariableSet_56.execute
# Layout: between IfThenElse_2@2704,4896 and VariableSet_56@3008,4912. Place at y=4800 (above).
vs_epwm_exec, vs_epwm_then, vs_epwm_value, vs_epwm_text = varset_byte(
    "EvadePeakWalkMode", 2848, 4800, N_VS_EPWM,
    exec_in_links=[],
    then_links=[],
    value_in_links=[],  # VG_RPWM_C
)
vg_rpwm_c_pin, vg_rpwm_c_text = varget_byte(
    "RollingPeakWalkMode", 2704, 4832, N_VG_RPWM_C,
    out_links=[f"{N_VS_EPWM} {vs_epwm_value}"],
)
vs_epwm_exec, vs_epwm_then, vs_epwm_value, vs_epwm_text = varset_byte(
    "EvadePeakWalkMode", 2848, 4800, N_VS_EPWM,
    exec_in_links=[],
    then_links=[],
    value_in_links=[f"{N_VG_RPWM_C} {vg_rpwm_c_pin}"],
)

# Phase 3 — evade-end reset
# Layout: between VariableSet_45@3296,5104 and VariableSet_2@3520,5104. Place at y=5000 (above).
vs_rpwm_rst_exec, vs_rpwm_rst_then, vs_rpwm_rst_value, vs_rpwm_rst_text = varset_byte(
    "RollingPeakWalkMode", 3392, 5000, N_VS_RPWM_RESET,
    exec_in_links=[],
    then_links=[],
    value_in_links=[],  # VG_PWM_C
)
vg_pwm_c_pin, vg_pwm_c_text = varget_byte(
    "PendingWalkMode", 3248, 5040, N_VG_PWM_C,
    out_links=[f"{N_VS_RPWM_RESET} {vs_rpwm_rst_value}"],
)
vs_rpwm_rst_exec, vs_rpwm_rst_then, vs_rpwm_rst_value, vs_rpwm_rst_text = varset_byte(
    "RollingPeakWalkMode", 3392, 5000, N_VS_RPWM_RESET,
    exec_in_links=[],
    then_links=[],
    value_in_links=[f"{N_VG_PWM_C} {vg_pwm_c_pin}"],
)

uv_t3d_parts = [
    "Begin Object",
    vg_hasevade_text,
    not_text,
    vg_pwm_a_text,
    vg_rpwm_a_text,
    gt_text,
    br1_text,
    br2_text,
    vg_pwm_b_text,
    vs_rpwm_upd_text,
    vg_rpwm_c_text,
    vs_epwm_text,
    vg_pwm_c_text,
    vs_rpwm_rst_text,
    "End Object",
]
# Note: UE actually expects a flat list of `Begin Object … End Object` blocks (no outer wrapper).
uv_t3d = "\n".join([
    vg_hasevade_text,
    not_text,
    vg_pwm_a_text,
    vg_rpwm_a_text,
    gt_text,
    br1_text,
    br2_text,
    vg_pwm_b_text,
    vs_rpwm_upd_text,
    vg_rpwm_c_text,
    vs_epwm_text,
    vg_pwm_c_text,
    vs_rpwm_rst_text,
])

with open(r"dumps/evade/step1_updatevariables_paste.t3d", "w", encoding="utf-8") as f:
    f.write(uv_t3d)

print("=== STEP 1 — UpdateVariables T3D ===")
print(f"Nodes generated: 13")
print(f"  Phase 1 (peak update): {N_VG_HASEVADE}, {N_NOT}, {N_VG_PWM_A}, {N_VG_RPWM_A}, {N_GREATER}, {N_BR1}, {N_BR2}, {N_VG_PWM_B}, {N_VS_RPWM_UPD}")
print(f"  Phase 2 (onset latch): {N_VG_RPWM_C}, {N_VS_EPWM}")
print(f"  Phase 3 (evade-end reset): {N_VG_PWM_C}, {N_VS_RPWM_RESET}")
print(f"\nExternal wires that PASTE references (will create wire on paste):")
print(f"  Branch_NEW_1.execute <-- VariableSet_43.then           [Phase 1 entry]")
print(f"  Branch_NEW_1.else    --> IfThenElse_2.execute          [Phase 1 exit: evade-active skip]")
print(f"  Branch_NEW_2.else    --> IfThenElse_2.execute          [Phase 1 exit: not-greater]")
print(f"  Set RollingPeak_Upd.then --> IfThenElse_2.execute      [Phase 1 exit: greater branch]")
print(f"  Set EvadePeak_Latch.execute <-- IfThenElse_2.then      [Phase 2 entry]")
print(f"  Set EvadePeak_Latch.then    --> VariableSet_56.execute [Phase 2 exit]")
print(f"  Set RollingPeak_Reset.execute <-- VariableSet_45.then  [Phase 3 entry]")
print(f"  Set RollingPeak_Reset.then    --> VariableSet_2.execute[Phase 3 exit]")
print(f"\nUser action after paste:")
print(f"  Phase 1: break wire VariableSet_43.then -> IfThenElse_2.execute (UE replaces with VarSet_43.then -> Branch_NEW_1.execute auto on paste if dest exists; else user manually disconnects extra wire if 2 wires appear)")
print(f"  Phase 2: break wire IfThenElse_2.then -> VariableSet_56.execute")
print(f"  Phase 3: break wire VariableSet_45.then -> VariableSet_2.execute")

# =====================================================================
# AnimRewindRecorderEmit T3D — splice 1 FormatText after FT_11
# =====================================================================
# Existing chain tail: FT_11.Result -> Knot_0.InputPin -> Knot_1.InputPin -> ... -> CallFunction_15.InText
# We splice a new FormatText with prev=FT_11.Result, plus 2 extra args (epwm, rpwm).
# Result -> Knot_0.InputPin (replaces FT_11.Result -> Knot_0).
#
# Format string: '{prev},"epwm"={epwm},"rpwm"={rpwm}'
# Need to use FT pin auto-gen — confirmed pattern from cps add (memory line 138-140).
#
# Nodes: 1 FT + 2 VarGet(byte) = 3 nodes.
#
# Existing FT_11.Result pin id (from dump):
EXISTING_FT11_RESULT = "K2Node_FormatText_11 CC6740D0420E93C08771719BCF4FEBDB"
# Existing Knot_0.InputPin:
EXISTING_KNOT0_INPUT = "K2Node_Knot_0 F313D91F44EADC9B73CA5F9F4D298755"
# Note: FT_11.Result also goes to CallFunction_15.InText — we replace that single endpoint? No:
# Dump shows FT_11.Result has TWO links: Knot_0.InputPin AND CallFunction_15.InText.
# For STEP 1 we splice only the Knot_0 path so the log line gets the new field; CallFunction_15.InText
# (whatever side branch) keeps the original. SAFER: leave both as-is and have the new FT consume
# FT_11.Result, but also connect new FT.Result to BOTH Knot_0 and CallFunction_15.InText to fully
# replace FT_11's outgoing.
#
# Decision: replace BOTH — the log emit path is the final string. We don't want two log lines.
EXISTING_CF15_INTEXT = "K2Node_CallFunction_15 InText"  # need exact pin id
# Let's look up CF_15 InText pin id below at script-build time via JSON.

import json as _json
emit_dump = _json.load(open("dumps/evade/AnimRewindRecorderEmit.json", "r", encoding="utf-8"))
cf15_intext_pin = None
ft11_result_pin = None
knot0_input_pin = None
for n in emit_dump["nodes"]:
    if n["id"] == "K2Node_CallFunction_15":
        for p in n["pins"]:
            if p["name"] == "InText":
                cf15_intext_pin = p["id"]
    if n["id"] == "K2Node_FormatText_11":
        for p in n["pins"]:
            if p["name"] == "Result":
                ft11_result_pin = p["id"]
    if n["id"] == "K2Node_Knot_0":
        for p in n["pins"]:
            if p["name"] == "InputPin":
                knot0_input_pin = p["id"]
assert cf15_intext_pin and ft11_result_pin and knot0_input_pin, "Failed to resolve external pin IDs"

# NOTE: external link refs are no longer used in T3D LinkedTo emission
# (one-sided links break paste). User wires them manually after paste.
# Keep variables for context comments only.
_EXT_FT11_RESULT = f"K2Node_FormatText_11 {ft11_result_pin}"
_EXT_KNOT0_INPUT = f"K2Node_Knot_0 {knot0_input_pin}"
_EXT_CF15_INTEXT = f"K2Node_CallFunction_15 {cf15_intext_pin}"
EXISTING_FT11_RESULT = ""  # sentinel — emitted as empty LinkedTo
EXISTING_KNOT0_INPUT = ""
EXISTING_CF15_INTEXT = ""

# Build new FT node (epwm + rpwm)
N_FT_NEW = "K2Node_FormatText_NEW_evadepeak"
N_VG_EPWM_EMIT = "K2Node_VariableGet_NEW_EPWM_emit"
N_VG_RPWM_EMIT = "K2Node_VariableGet_NEW_RPWM_emit"

ft_new_format = guid32()
ft_new_result = guid32()
ft_new_prev = guid32()
ft_new_epwm = guid32()
ft_new_rpwm = guid32()
ft_new_node_guid = node_guid()

vg_epwm_pin, vg_epwm_text = varget_byte(
    "EvadePeakWalkMode", 11200, 400, N_VG_EPWM_EMIT,
    out_links=[f"{N_FT_NEW} {ft_new_epwm}"],
)
vg_rpwm_pin, vg_rpwm_text = varget_byte(
    "RollingPeakWalkMode", 11200, 460, N_VG_RPWM_EMIT,
    out_links=[f"{N_FT_NEW} {ft_new_rpwm}"],
)

# FormatText: pins = Format (input, hidden literal), Result (output), prev, epwm, rpwm
# When FormatText is added via add_node API, format string '{prev},"epwm"={epwm},"rpwm"={rpwm}'
# auto-generates pins for {prev}, {epwm}, {rpwm}. T3D needs to emit those pins explicitly.
# Pin types: prev=text(matches FT_11.Result text type), epwm/rpwm=byte (auto-promote).
ft_text = f"""Begin Object Class=/Script/BlueprintGraph.K2Node_FormatText Name="{N_FT_NEW}"
   PinNames=("prev","epwm","rpwm")
   CachedFormatText=NSLOCTEXT("","","{{prev}},\\"epwm\\"={{epwm}},\\"rpwm\\"={{rpwm}}")
   NodePosX=11440
   NodePosY=400
   NodeGuid={ft_new_node_guid}
   CustomProperties Pin (PinId={ft_new_format},PinName="Format",PinType.PinCategory="text",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultTextValue=NSLOCTEXT("","","{{prev}},\\"epwm\\"={{epwm}},\\"rpwm\\"={{rpwm}}"),AutogeneratedDefaultValue="",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=True,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={ft_new_result},PinName="Result",Direction="EGPD_Output",PinType.PinCategory="text",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={ft_new_prev},PinName="prev",PinType.PinCategory="text",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={ft_new_epwm},PinName="epwm",PinType.PinCategory="wildcard",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(EdGraphPin'"{N_VG_EPWM_EMIT} {vg_epwm_pin}"'),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId={ft_new_rpwm},PinName="rpwm",PinType.PinCategory="wildcard",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(EdGraphPin'"{N_VG_RPWM_EMIT} {vg_rpwm_pin}"'),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object"""

emit_t3d = "\n".join([vg_epwm_text, vg_rpwm_text, ft_text])

with open(r"dumps/evade/step1_animrec_emit_paste.t3d", "w", encoding="utf-8") as f:
    f.write(emit_t3d)

print(f"\n=== STEP 1 — AnimRewindRecorderEmit T3D ===")
print(f"Nodes generated: 3 (1 FormatText + 2 VariableGet)")
print(f"  New FT: {N_FT_NEW}")
print(f"  Format: '{{prev}},\"epwm\"={{epwm}},\"rpwm\"={{rpwm}}'")
print(f"  prev<- FT_11.Result")
print(f"  Result -> Knot_0.InputPin + CallFunction_15.InText (replaces FT_11.Result wires)")
print(f"\nUser action after paste:")
print(f"  Break two existing wires FT_11.Result -> Knot_0.InputPin and FT_11.Result -> CallFunction_15.InText")
print(f"  (UE may handle this auto on LinkedTo replace; if duplicate wires appear, delete the old ones.)")
