"""Generate T3D paste chunk for STEP 2 (TrjFutureVelocity-based PendingWalkMode predictor).

Target graph : UpdateStates (function)
Asset        : /Game/Art/Character/PC/PC_01/Blueprint/PC_01_ABP

Splice plan:
    BEFORE   : VG_5.Speed2D -> CF_2.Speed -> VS_15.PendingWalkMode
    AFTER    : VG_5.Speed2D -> Select.Option_0
                              VSizeXY(VG_TFV.TrjFutureVelocity) -> Select.Option_1
                              AND(VG_HasEvade, VG_IsLockOn) -> Select.Index
                              Select.ReturnValue -> CF_2.Speed -> VS_15 (unchanged)

Six new nodes (zero new variables — all referenced vars already exist in ABP):
    1. VariableGet HasEvade (bool)
    2. VariableGet IsLockOn (bool)
    3. CommutativeAssociativeBinaryOperator BooleanAND (KismetMathLibrary)
    4. VariableGet TrjFutureVelocity (struct:Vector)
    5. CallFunction VSizeXY (KismetMathLibrary; FVector -> double)
    6. K2Node_Select with bool Index, double options

External wires (user does after paste — 1 break + 2 connect):
    BREAK:   VG_5.Speed2D -> CF_2.Speed
    CONNECT: VG_5.Speed2D -> Select.Option_0
    CONNECT: Select.ReturnValue -> CF_2.Speed

Output: dumps/evade/step2_updatestates_paste.t3d
"""
from __future__ import annotations

import uuid


def guid32() -> str:
    return uuid.uuid4().hex.upper()


def node_guid() -> str:
    return uuid.uuid4().hex.upper()


# ---------------------------------------------------------------------------
# Node emitters — internal LinkedTo only; external pins use LinkedTo=()
# so user wires them in editor after paste (mirrors STEP 1 pattern).
# ---------------------------------------------------------------------------

def varget_bool(name: str, posx: int, posy: int, node_name: str, out_links: list[str]) -> tuple[str, str]:
    pin_id = guid32()
    linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    text = (
        f'Begin Object Class=/Script/BlueprintGraph.K2Node_VariableGet Name="{node_name}"\n'
        f'   VariableReference=(MemberName="{name}",bSelfContext=True)\n'
        f'   NodePosX={posx}\n'
        f'   NodePosY={posy}\n'
        f'   NodeGuid={node_guid()}\n'
        f'   CustomProperties Pin (PinId={pin_id},PinName="{name}",Direction="EGPD_Output",'
        f'PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'End Object'
    )
    return pin_id, text


def varget_vector(name: str, posx: int, posy: int, node_name: str, out_links: list[str]) -> tuple[str, str]:
    """K2Node_VariableGet for struct:Vector (FVector)."""
    pin_id = guid32()
    linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    text = (
        f'Begin Object Class=/Script/BlueprintGraph.K2Node_VariableGet Name="{node_name}"\n'
        f'   VariableReference=(MemberName="{name}",bSelfContext=True)\n'
        f'   NodePosX={posx}\n'
        f'   NodePosY={posy}\n'
        f'   NodeGuid={node_guid()}\n'
        f'   CustomProperties Pin (PinId={pin_id},PinName="{name}",Direction="EGPD_Output",'
        f'PinType.PinCategory="struct",PinType.PinSubCategory="",'
        f'PinType.PinSubCategoryObject=ScriptStruct\'"/Script/CoreUObject.Vector"\','
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="(X=0.000000,Y=0.000000,Z=0.000000)",'
        f'AutogeneratedDefaultValue="(X=0.000000,Y=0.000000,Z=0.000000)",LinkedTo=({linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'End Object'
    )
    return pin_id, text


def boolean_and(node_name: str, posx: int, posy: int,
                a_in_links: list[str], b_in_links: list[str],
                out_links: list[str]) -> tuple[str, str, str, str]:
    """K2Node_CommutativeAssociativeBinaryOperator BooleanAND (KismetMathLibrary).

    Returns (a_pin, b_pin, ret_pin, text).
    """
    self_pin = guid32()
    a_pin = guid32()
    b_pin = guid32()
    ret_pin = guid32()
    a_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in a_in_links)
    b_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in b_in_links)
    ret_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    text = (
        f'Begin Object Class=/Script/BlueprintGraph.K2Node_CommutativeAssociativeBinaryOperator Name="{node_name}"\n'
        f'   bIsPureFunc=True\n'
        f'   FunctionReference=(MemberParent=Class\'"/Script/Engine.KismetMathLibrary"\',MemberName="BooleanAND")\n'
        f'   NodePosX={posx}\n'
        f'   NodePosY={posy}\n'
        f'   NodeGuid={node_guid()}\n'
        f'   CustomProperties Pin (PinId={self_pin},PinName="self",'
        f'PinFriendlyName=NSLOCTEXT("K2Node","Target","Target"),'
        f'PinToolTip="Target\\nKismet Math Library Reference",'
        f'PinType.PinCategory="object",PinType.PinSubCategory="",'
        f'PinType.PinSubCategoryObject=Class\'"/Script/Engine.KismetMathLibrary"\','
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultObject="/Script/Engine.Default__KismetMathLibrary",'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'   CustomProperties Pin (PinId={a_pin},PinName="A",PinType.PinCategory="bool",'
        f'PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({a_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'   CustomProperties Pin (PinId={b_pin},PinName="B",PinType.PinCategory="bool",'
        f'PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({b_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'   CustomProperties Pin (PinId={ret_pin},PinName="ReturnValue",Direction="EGPD_Output",'
        f'PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({ret_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'End Object'
    )
    return a_pin, b_pin, ret_pin, text


def vsize_xy(node_name: str, posx: int, posy: int,
             a_in_links: list[str], out_links: list[str]) -> tuple[str, str, str]:
    """K2Node_CallFunction KismetMathLibrary::VSizeXY (FVector -> double).

    Returns (a_pin, ret_pin, text).
    """
    self_pin = guid32()
    a_pin = guid32()
    ret_pin = guid32()
    a_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in a_in_links)
    ret_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    text = (
        f'Begin Object Class=/Script/BlueprintGraph.K2Node_CallFunction Name="{node_name}"\n'
        f'   bIsPureFunc=True\n'
        f'   FunctionReference=(MemberParent=Class\'"/Script/Engine.KismetMathLibrary"\',MemberName="VSizeXY")\n'
        f'   NodePosX={posx}\n'
        f'   NodePosY={posy}\n'
        f'   NodeGuid={node_guid()}\n'
        f'   CustomProperties Pin (PinId={self_pin},PinName="self",'
        f'PinFriendlyName=NSLOCTEXT("K2Node","Target","Target"),'
        f'PinToolTip="Target\\nKismet Math Library Reference",'
        f'PinType.PinCategory="object",PinType.PinSubCategory="",'
        f'PinType.PinSubCategoryObject=Class\'"/Script/Engine.KismetMathLibrary"\','
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultObject="/Script/Engine.Default__KismetMathLibrary",'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'   CustomProperties Pin (PinId={a_pin},PinName="A",PinType.PinCategory="struct",'
        f'PinType.PinSubCategory="",'
        f'PinType.PinSubCategoryObject=ScriptStruct\'"/Script/CoreUObject.Vector"\','
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="(X=0.000000,Y=0.000000,Z=0.000000)",'
        f'AutogeneratedDefaultValue="(X=0.000000,Y=0.000000,Z=0.000000)",LinkedTo=({a_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'   CustomProperties Pin (PinId={ret_pin},PinName="ReturnValue",Direction="EGPD_Output",'
        f'PinType.PinCategory="real",PinType.PinSubCategory="double",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="0.0",AutogeneratedDefaultValue="0.0",LinkedTo=({ret_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'End Object'
    )
    return a_pin, ret_pin, text


def select_double(node_name: str, posx: int, posy: int,
                  opt0_links: list[str], opt1_links: list[str],
                  index_links: list[str], out_links: list[str]) -> tuple[str, str, str, str, str]:
    """K2Node_Select with bool Index, double Option_0/Option_1, double ReturnValue.

    Mirrors K2Node_Select_0 (byte) found in UpdateStates but type=double.

    Returns (opt0_pin, opt1_pin, index_pin, ret_pin, text).
    """
    opt0_pin = guid32()
    opt1_pin = guid32()
    index_pin = guid32()
    ret_pin = guid32()
    opt0_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in opt0_links)
    opt1_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in opt1_links)
    index_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in index_links)
    ret_linked = ",".join(f"EdGraphPin'\"{l}\"'" for l in out_links)
    text = (
        f'Begin Object Class=/Script/BlueprintGraph.K2Node_Select Name="{node_name}"\n'
        f'   NumOptionPins=2\n'
        f'   IndexPinType=(PinCategory="bool",PinSubCategory="",PinSubCategoryObject=None,'
        f'PinSubCategoryMemberReference=(),PinValueType=(),ContainerType=None,'
        f'bIsReference=False,bIsConst=False,bIsWeakPointer=False,'
        f'bIsUObjectWrapper=False,bSerializeAsSinglePrecisionFloat=False)\n'
        f'   NodePosX={posx}\n'
        f'   NodePosY={posy}\n'
        f'   NodeGuid={node_guid()}\n'
        f'   CustomProperties Pin (PinId={opt0_pin},PinName="Option 0",'
        f'PinType.PinCategory="real",PinType.PinSubCategory="double",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="0.0",AutogeneratedDefaultValue="0.0",LinkedTo=({opt0_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'   CustomProperties Pin (PinId={opt1_pin},PinName="Option 1",'
        f'PinType.PinCategory="real",PinType.PinSubCategory="double",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="0.0",AutogeneratedDefaultValue="0.0",LinkedTo=({opt1_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'   CustomProperties Pin (PinId={index_pin},PinName="Index",PinType.PinCategory="bool",'
        f'PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="false",AutogeneratedDefaultValue="false",LinkedTo=({index_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'   CustomProperties Pin (PinId={ret_pin},PinName="ReturnValue",Direction="EGPD_Output",'
        f'PinType.PinCategory="real",PinType.PinSubCategory="double",PinType.PinSubCategoryObject=None,'
        f'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,'
        f'PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,'
        f'PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,'
        f'DefaultValue="0.0",AutogeneratedDefaultValue="0.0",LinkedTo=({ret_linked}),'
        f'PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,'
        f'bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)\n'
        f'End Object'
    )
    return opt0_pin, opt1_pin, index_pin, ret_pin, text


# ---------------------------------------------------------------------------
# Topology — internal wiring resolved in dependency order
# ---------------------------------------------------------------------------

N_VG_HASEVADE = "K2Node_VariableGet_NEW_S2_HasEvade"
N_VG_ISLOCKON = "K2Node_VariableGet_NEW_S2_IsLockOn"
N_AND = "K2Node_CommutativeAssociativeBinaryOperator_NEW_S2_AND"
N_VG_TFV = "K2Node_VariableGet_NEW_S2_TFV"
N_VSIZEXY = "K2Node_CallFunction_NEW_S2_VSizeXY"
N_SELECT = "K2Node_Select_NEW_S2"

# Layout: place left of CF_2 @ (2000, 528). Use empty region around (1320-1820, 240-440).
POS_VG_HASEVADE = (1320, 240)
POS_VG_ISLOCKON = (1320, 300)
POS_AND = (1500, 264)
POS_VG_TFV = (1320, 380)
POS_VSIZEXY = (1500, 372)
POS_SELECT = (1700, 320)

# Step 1: build Select first (sink) with placeholders, then walk back.
opt0_pin, opt1_pin, index_pin, sel_ret_pin, sel_text = select_double(
    N_SELECT, *POS_SELECT,
    opt0_links=[],   # external: VG_5.Speed2D — user wires
    opt1_links=[],   # will be VSizeXY.ReturnValue
    index_links=[],  # will be AND.ReturnValue
    out_links=[],    # external: CF_2.Speed — user wires
)

# AND.ReturnValue -> Select.Index
and_a_pin, and_b_pin, and_ret_pin, and_text = boolean_and(
    N_AND, *POS_AND,
    a_in_links=[],   # VG_HasEvade
    b_in_links=[],   # VG_IsLockOn
    out_links=[f"{N_SELECT} {index_pin}"],
)

# VG_HasEvade -> AND.A
vg_he_pin, vg_he_text = varget_bool(
    "HasEvade", *POS_VG_HASEVADE, N_VG_HASEVADE,
    out_links=[f"{N_AND} {and_a_pin}"],
)

# VG_IsLockOn -> AND.B
vg_lo_pin, vg_lo_text = varget_bool(
    "IsLockOn", *POS_VG_ISLOCKON, N_VG_ISLOCKON,
    out_links=[f"{N_AND} {and_b_pin}"],
)

# Patch AND with back-links
and_a_pin, and_b_pin, and_ret_pin, and_text = boolean_and(
    N_AND, *POS_AND,
    a_in_links=[f"{N_VG_HASEVADE} {vg_he_pin}"],
    b_in_links=[f"{N_VG_ISLOCKON} {vg_lo_pin}"],
    out_links=[f"{N_SELECT} {index_pin}"],
)

# VSizeXY.ReturnValue -> Select.Option_1
vsx_a_pin, vsx_ret_pin, vsx_text = vsize_xy(
    N_VSIZEXY, *POS_VSIZEXY,
    a_in_links=[],   # VG_TFV
    out_links=[f"{N_SELECT} {opt1_pin}"],
)

# VG_TFV -> VSizeXY.A
vg_tfv_pin, vg_tfv_text = varget_vector(
    "TrjFutureVelocity", *POS_VG_TFV, N_VG_TFV,
    out_links=[f"{N_VSIZEXY} {vsx_a_pin}"],
)

# Patch VSizeXY with back-link
vsx_a_pin, vsx_ret_pin, vsx_text = vsize_xy(
    N_VSIZEXY, *POS_VSIZEXY,
    a_in_links=[f"{N_VG_TFV} {vg_tfv_pin}"],
    out_links=[f"{N_SELECT} {opt1_pin}"],
)

# Patch Select with all back-links resolved
opt0_pin, opt1_pin, index_pin, sel_ret_pin, sel_text = select_double(
    N_SELECT, *POS_SELECT,
    opt0_links=[],
    opt1_links=[f"{N_VSIZEXY} {vsx_ret_pin}"],
    index_links=[f"{N_AND} {and_ret_pin}"],
    out_links=[],
)

t3d = "\n".join([vg_he_text, vg_lo_text, and_text, vg_tfv_text, vsx_text, sel_text])

with open(r"dumps/evade/step2_updatestates_paste.t3d", "w", encoding="utf-8") as f:
    f.write(t3d)

print("=== STEP 2 — UpdateStates T3D ===")
print("Target asset : /Game/Art/Character/PC/PC_01/Blueprint/PC_01_ABP")
print("Target graph : UpdateStates (function)")
print()
print("Nodes generated (6):")
print(f"  1. {N_VG_HASEVADE:50s} (bool)")
print(f"  2. {N_VG_ISLOCKON:50s} (bool)")
print(f"  3. {N_AND:50s} (BooleanAND)")
print(f"  4. {N_VG_TFV:50s} (struct:Vector)")
print(f"  5. {N_VSIZEXY:50s} (KismetMathLibrary::VSizeXY)")
print(f"  6. {N_SELECT:50s} (Select, bool Index, double options)")
print()
print("Internal wires (resolved in T3D):")
print(f"  VG_HasEvade.HasEvade   -> AND.A")
print(f"  VG_IsLockOn.IsLockOn   -> AND.B")
print(f"  AND.ReturnValue        -> Select.Index")
print(f"  VG_TFV.TrjFutureVelocity -> VSizeXY.A")
print(f"  VSizeXY.ReturnValue    -> Select.Option_1")
print()
print("External wires (USER ACTION after paste in UpdateStates):")
print("  BREAK   : VG_5(Get Speed2D).Speed2D -> CF_2(Calc Walk Mode).Speed")
print("  CONNECT : VG_5(Get Speed2D).Speed2D -> Select.Option_0")
print("  CONNECT : Select.ReturnValue        -> CF_2(Calc Walk Mode).Speed")
print()
print("Output:", "dumps/evade/step2_updatestates_paste.t3d")
